version: "3.9"

services:
  app:
    image: filesharing-app
    container_name: filesharing-combined
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/html:/var/www/certbot:ro
    restart: always
