version: "3.9"

services:
  filesharing:
    image: filesharing-app:2
    container_name: filesharing
    env_file: .env
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/var/www/certbot
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - filesharing
    restart: always

