# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Code compilation (Syntax Check)
      run: |
        FILES_COUNT=$(find . -type f -name "*.js" -not -path "./node_modules/*" -not -path "./dist/*" | wc -l)
        echo "Total files found for checking: $FILES_COUNT"
        find . -type f -name "*.js" \
            -not -path "./node_modules/*" \
            -not -path "./dist/*" \
            -print \
            -exec node --check {} +

  # gitleaks-scans:
  #   runs-on: ubuntu-latest
  #   needs: compile
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Gitleaks Setup
  #     uses: gitleaks/gitleaks-actions@v2
  #   - name: Gitleaks Scan
  #     run: |
  #       gitleaks detect --source ./ --exit-code 1 --verbose --redact --config .gitleaks.toml

  gitleaks-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        # env:
        #   GITHUB_TOKEN: ${{ secrets.LEAKS_TOKEN }}
        # with:
          # Note: The action handles the exit code 1 automatically!
          # args: detect --source . --verbose --redact
      - name: Gitleaks scan
        run: |
          gitleaks detect --source ./ --exit-code 1

      - name: Install Production Dependencies
        run: npm ci --omit=dev --legacy-peer-deps

  trivyfs-scan:
    name: trivyfs scanning
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignored-unfixed: true
          vul-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: trivyfs-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          args: >
            -Dsonar.projectKey=filesharing-app
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64

          # triple tags
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/filesharing-app:latest
            ${{ secrets.DOCKER_USERNAME }}/filesharing-app:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/filesharing-app:${{ github.ref_name }}
      - name: Check my variables
        run: |
          echo "The Short Ref is: ${{ github.ref_name }}"
          echo "The Full Ref is: ${{ github.ref }}"
          echo "The Commit SHA is: ${{ github.sha }}"
          
      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

        
