# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Code compilation (Syntax Check)
      run: |
        FILES_COUNT=$(find . -type f -name "*.js" -not -path "./node_modules/*" -not -path "./dist/*" | wc -l)
        echo "Total files found for checking: $FILES_COUNT"
        find . -type f -name "*.js" \
            -not -path "./node_modules/*" \
            -not -path "./dist/*" \
            -print \
            -exec node --check {} +

  # gitleaks-scans:
  #   runs-on: ubuntu-latest
  #   needs: compile
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Gitleaks Setup
  #     uses: gitleaks/gitleaks-actions@v2
  #   - name: Gitleaks Scan
  #     run: |
  #       gitleaks detect --source ./ --exit-code 1 --verbose --redact --config .gitleaks.toml

  gitleaks-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        # env:
        #   GITHUB_TOKEN: ${{ secrets.LEAKS_TOKEN }}
        # with:
          # Note: The action handles the exit code 1 automatically!
          # args: detect --source . --verbose --redact
      - name: Gitleaks scan
        run: |
          gitleaks detect --source ./ --exit-code 1

      - name: Install Production Dependencies
        run: npm ci --omit=dev --legacy-peer-deps

      - name: Verify runtime dependency versions (repo)
        run: |
          echo "Verifying dependencies from node_modules:"
          npm ls cross-spawn glob || true

  trivyfs-scan:
    name: trivyfs scanning
    runs-on: ubuntu-latest
    needs: gitleaks-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  sonarqube-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: trivyfs-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        with:
          args: >
            -Dsonar.projectKey=filesharing-app
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

  build-and-push-docker-image:
    name: Build, Scan and Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #handling the lowercase conversion for your username. As docker don't accept captial letters and some special caracters.
      - name: Lowercase repository name
        id: lower_repo
        run: |
          # 1. Get the username from secrets
          USER_INPUT="${{ secrets.DOCKER_USERNAME }}"
          
          # 2. Lowercase the username
          LOW_USER="${USER_INPUT,,}"
          
          # 3. Use 'sed' to replace any character that IS NOT a-z, 0-9, -, or _ with a dash
          # The [^a-z0-9_-] means "anything NOT in this list"
          CLEAN_USER=$(echo "$LOW_USER" | sed 's/[^a-z0-9_-]/-/g')
          
          # 4. Combine with app name and export
          echo "repository=${CLEAN_USER}/filesharing-app" >> $GITHUB_OUTPUT

      #Debug step to see your refs in the logs (outside of Build step)
      - name: Check variables
        run: |
          echo "The Short Ref is: ${{ github.ref_name }}"
          echo "The Commit SHA is: ${{ github.sha }}"
          echo "Final Repo Name: ${{ steps.lower_repo.outputs.repository }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          # Only installing the emulator for the target architecture as we are running in amd64 so no need for that
          platforms: arm64

      # We build only for the runner's native architecture (amd64) and load it into the daemon
      - name: Build AMD64 image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          platforms: linux/amd64
          tags: ${{ steps.lower_repo.outputs.repository }}:scan-temp
          cache-from: type=gha,scope=amd64
          cache-to: type=gha,mode=max,scope=amd64

      - name: Verify dependency versions inside image
        run: |
          docker run --rm ${{ steps.lower_repo.outputs.repository }}:scan-temp \
            sh -c "node -v && npm ls cross-spawn glob || true"

      # If this fails with exit code 1, the workflow stops here and won't push
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ steps.lower_repo.outputs.repository }}:scan-temp'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      # ARM64 cache warm-up build
      - name: Warm up ARM64 cache (no push, no load)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          push: false
          cache-from: type=gha,scope=arm64
          cache-to: type=gha,mode=max,scope=arm64

      # This will push both amd64 and arm64. Docker Buildx will reuse the cache from Step 1.
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          #no-cache: true
          platforms: linux/amd64,linux/arm64
          # Using GitHub Actions cache for lightning-fast rebuilds
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          cache-from: |
            type=gha,scope=amd64
            type=gha,scope=arm64
          cache-to: |
            type=gha,mode=max,scope=amd64
            type=gha,mode=max,scope=arm64
          
          # 3. Use the lowercase 'repository' output here
          tags: |
            ${{ steps.lower_repo.outputs.repository }}:latest
            ${{ steps.lower_repo.outputs.repository }}:${{ github.sha }}
            ${{ github.ref_type == 'tag' && format('{0}:{1}', steps.lower_repo.outputs.repository, github.ref_name) || format('{0}:{1}', steps.lower_repo.outputs.repository, github.ref_name) }}


  deploy:
    name: Deploy to Server
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Copy the docker-compose.yml from your repo to the server
      - name: Copy docker-compose.yml via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/filesharing-app"

      # 2. Run the SSH commands
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Check/Install Docker logic
            if ! [ -x "$(command -v docker)" ]; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
              newgrp docker
            fi

            cd ~/filesharing-app

            # Create the .env file from GitHub Secrets (Still needed as .env isn't in repo)
            cat <<EOF > .env
            # --- Docker Image Config ---
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            DOCKER_IMAGE_NAME=filesharing-app
            DOCKER_IMAGE_TAG=latest
            PORT=3000
            MONGODB_URL=${{ secrets.MONGODB_URL }}
            BASE_URL=${{ secrets.BASE }}
            DOWNLOAD_TOKEN_EXPIRY_MIN=30
            MAX_FILE_SIZE_BYTES=104857600 
            EOF

            # Login and Start using the file we just SCP'd
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans

  health-check:
    name: Verify Deployment
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check HTTP Status
        run: |
          # 10 seconds to give the app time to boot
          sleep 10
          curl -f https://dileep.dpdns.org || exit 1
            
      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

        
