# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Code compilation (Syntax Check)
      run: |
        FILES_COUNT=$(find . -type f -name "*.js" -not -path "./node_modules/*" -not -path "./dist/*" | wc -l)
        echo "Total files found for checking: $FILES_COUNT"
        find . -type f -name "*.js" \
            -not -path "./node_modules/*" \
            -not -path "./dist/*" \
            -print \
            -exec node --check {} +

  # gitleaks-scans:
  #   runs-on: ubuntu-latest
  #   needs: compile
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - name: Gitleaks Setup
  #     uses: gitleaks/gitleaks-actions@v2
  #   - name: Gitleaks Scan
  #     run: |
  #       gitleaks detect --source ./ --exit-code 1 --verbose --redact --config .gitleaks.toml

  gitleaks-scan:
    name: Secret Scanning
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.LEAKS_TOKEN }}
        with:
          # Note: The action handles the exit code 1 automatically!
          args: detect --source . --verbose --redact

      - name: Install Production Dependencies
        run: npm ci --omit=dev --legacy-peer-deps

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test

        
